imports:
    - { resource: 'services.yml' }
    - { resource: '../../packages/**/config/config.yml' }
    - { resource: '../../packages/**/src/config/config.yml' }

parameters:
    merge_sections: ['require', 'require-dev', 'autoload', 'autoload-dev', 'repositories']
    package_directories:
        - 'packages'
    data_to_append: []
    data_to_remove: []
    package_alias_format: '<major>.<minor>-dev'
