services:
    _defaults:
        public: true
        autowire: true

    Symplify\MonorepoBuilder\:
        resource: '..'
        exclude: '../{Contract,Exception}'

    Symplify\PackageBuilder\Yaml\ParametersMerger: ~

    Symplify\PackageBuilder\Console\ConfigAwareApplication:
        calls:
            - ['setDispatcher', ['@Symfony\Component\EventDispatcher\EventDispatcher']]

    # SymfonyStyle
    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Input\InputInterface:
        alias: 'Symfony\Component\Console\Input\ArgvInput'
    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: 'Symfony\Component\Console\Output\ConsoleOutput'
    Symfony\Component\Console\Style\SymfonyStyle: ~

    Symfony\Component\EventDispatcher\EventDispatcher: ~

    # alias needed for Symfony Console setter
    Symfony\Component\EventDispatcher\EventDispatcherInterface:
        alias: 'Symfony\Component\EventDispatcher\EventDispatcher'

    Symfony\Component\Filesystem\Filesystem: ~
